spring.application.name=velogexpress

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

sendgrid.api-key=${SENDGRID_API_KEY}
mail.hostinger.username=${HOSTINGER_MAIL_USERNAME:info@velogxpress.com}
mail.hostinger.password=${HOSTINGER_MAIL_PASSWORD}
notification.api-key=${NOTIFICATION_API_KEY}

r2.account-id=${R2_ACCOUNT_ID}
r2.access-key-id=${R2_ACCESS_KEY_ID}
r2.secret-access-key=${R2_SECRET_ACCESS_KEY}
r2.bucket-name=${R2_BUCKET_NAME}
r2.public-url=${R2_PUBLIC_URL}

spring.data.redis.url=${REDIS_URL}
spring.cache.type=redis

server.port=9400

spring.jpa.hibernate.ddl-auto=validate
spring.codec.max-in-memory-size=20MB
spring.jpa.open-in-view=false

# Taille max d'un fichier
spring.servlet.multipart.max-file-size=20MB

# Taille max de la requete complete
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=/srv/velog/api/uploads/
spring.web.resources.static-locations=file:/srv/velog/api/uploads/
spring.mvc.static-path-pattern=/uploads/**

#file.upload-dir=/Users/macceaumarcelin/IdeaProjects/Velog/uploads/
#spring.web.resources.static-locations=file:/Users/macceaumarcelin/IdeaProjects/Velog/uploads/
#spring.mvc.static-path-pattern=/uploads/**
